language:
  - c++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gfortran-4.8
      - build-essential
      - openmpi-bin
      - libopenmpi-dev
      - cmake
      - git
      - liblapack-dev
      - liblapack3gf
      - libblas-dev
      - libblas3gf

before_install:
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX

install:
  - sh conf/install-deps.sh
  - mkdir build; cd build
  - CC=gcc-4.8 CXX=g++-4.8 FC=gfortran-4.8 cmake ../ -DPETSC_DIR=/home/travis/petsc -DEIGEN_INCLUDE=/home/travis/eigen -DCMAKE_BUILD_TYPE=Release
  - make VERBOSE=1
  - make salvus_test VERBOSE=1

  # Install salvus_data as well.
  - cd; cd build
  - git clone https://github.com/SalvusHub/salvus_data.git

script:
  - cd salvus_data/new_unit_tests
  - sh ./run_travis.sh

cache:
  directories:
    - $HOME/petsc
