language:
  - c++

addons:
  apt:
    packages:
      - build-essential
      - gfortran
      - perl
      - g++
      - gcc
      - cmake
      - m4
      - git
      - liblapack-dev
      - liblapack-doc
      - liblapack3gf
      - libblas-dev
      - libblas3gf
      - openmpi-bin
      - openmpi-common
      - libopenmpi-dev

before_install:
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX

install:
  - sh conf/install-deps.sh
  - cp conf/CMakeLists.txt.travis ./CMakeLists.txt
  - mkdir build; cd build
  - cmake ../
  - make

script:
  - ls
