language:
  - c++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gfortran-4.8
      - build-essential
      - perl
      - cmake
      - m4
      - git
      - liblapack-dev
      - liblapack-doc
      - liblapack3gf
      - libblas-dev
      - libblas3gf

before_install:
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX
  - sh conf/install-deps.sh

install:
  - cp conf/CMakeLists.txt.travis ./CMakeLists.txt
  - mkdir build; cd build
  - cmake ../
  - make
  - make salvus_test

  # Install salvus_data as well.
  - cd; cd build
  - git clone https://github.com/SalvusHub/salvus_data.git

script:
  - cd salvus_data/unit_test_meshes
  - ./run_2d_acoustic_test.sh
